export const STUDENT_HEADER: string[] = [
  'studentId',
  'email',
  'firstName',
  'middleName',
  'lastName',
  'dateOfBirth',
  'gender',
  'className',
  'major',
  'courseYear',
  'academicYear',
  'projectName',
  'extraData',
];

export const STUDENT_HEADER_ALIASES: Record<string, string> = {
  student_id: 'studentId',
  studentid: 'studentId',
  first_name: 'firstName',
  firstname: 'firstName',
  middle_name: 'middleName',
  middlename: 'middleName',
  last_name: 'lastName',
  lastname: 'lastName',
  date_of_birth: 'dateOfBirth',
  dateofbirth: 'dateOfBirth',
  class_name: 'className',
  classname: 'className',
  course_year: 'courseYear',
  courseyear: 'courseYear',
  academic_year: 'academicYear',
  academicyear: 'academicYear',
  project_name: 'projectName',
  projectname: 'projectName',
  extra_data: 'extraData',
  extradata: 'extraData',
  gmail: 'email',
};
