export const STUDENT_HEADER: string[] = [
  'studentId',
  'email',
  'firstName',
  'middleName',
  'lastName',
  'dateOfBirth',
  'gender',
  'className',
  'major',
  'courseYear',
  'academicYear',
  'projectName',
  'extraData',
];

export const STUDENT_REQUIRED_HEADERS: string[] = [
  'studentId',
  'email',
  'className',
  'major',
];

export const STUDENT_IMPORT_FIELDS = new Set([...STUDENT_HEADER, 'fullName']);

export const STUDENT_HEADER_ALIASES: Record<string, string> = {
  studentid: 'studentId',
  mssv: 'studentId',
  masinhvien: 'studentId',
  email: 'email',
  gmail: 'email',
  firstname: 'firstName',
  ten: 'firstName',
  middlename: 'middleName',
  tenlot: 'middleName',
  tendem: 'middleName',
  lastname: 'lastName',
  ho: 'lastName',
  fullname: 'fullName',
  hoten: 'fullName',
  name: 'fullName',
  dateofbirth: 'dateOfBirth',
  ngaysinh: 'dateOfBirth',
  dob: 'dateOfBirth',
  gender: 'gender',
  gioitinh: 'gender',
  classname: 'className',
  lop: 'className',
  major: 'major',
  khoa: 'major',
  nganh: 'major',
  chuyennganh: 'major',
  courseyear: 'courseYear',
  khoahoc: 'courseYear',
  nambatdau: 'courseYear',
  academicyear: 'academicYear',
  nienkhoa: 'academicYear',
  projectname: 'projectName',
  detai: 'projectName',
  thesis: 'projectName',
  phone: 'phone',
  sdt: 'phone',
  sodienthoai: 'phone',
  address: 'address',
  diachi: 'address',
  extradata: 'extraData',
  extrajson: 'extraData',
  jsondata: 'extraData',
  dulieubosung: 'extraData',
  json: 'extraData',
};
