ALTER TYPE "ReportStatus" ADD VALUE IF NOT EXISTS 'PENDING_TEACHER';
ALTER TYPE "ReportStatus" ADD VALUE IF NOT EXISTS 'APPROVED_BY_TEACHER';
ALTER TYPE "ReportStatus" ADD VALUE IF NOT EXISTS 'ARCHIVED';
